- docs/features/asa.md
This is a proposed solution to this issue: https://github.com/algorand/docs/issues/100 and could be applied to this issue later too: https://github.com/algorand/docs/issues/57
Some of the code snippets are better understood within the context of the full code example, which is located at the bottom of the page. We received feedback that people didn't even know about this full example.  
Put a header above the full code example at the bottom of the page so that it shows up in the Table of Contents and becomes linkable. Then place a link to it underneath each code snippet.
There are a number of ways you could solve this problem. I've listed two below but you can imagine variations of these too. It's not clear which one is best. I chose the most subtle one with the assumption that it would …
> Added links to full code under each of the snippets.

- docs/reference/algorand-networks/betanet.md
Bump the version number to reflect the current version of BetaNet.
> Update BetaNet version to 2.0.14

- docs/reference/algorand-networks/mainnet.md
- docs/reference/algorand-networks/testnet.md
Algorand is updating this morning to 2.0.7-stable, so updating docs to reflect this.
> Update TestNet and MainNet to 2.0.7-stable

- docs/reference/algorand-networks/betanet.md
BetaNet is scheduled to update to 2.0.15 on 6/25/2020 at 9:30am.
> Update BetaNet current version to 2.0.15

- docs/reference/algorand-networks/mainnet.md
- docs/reference/algorand-networks/testnet.md
Update documentation to point TestNet/MainNet to 2.0.8-stable. Effective 9/26/2020 at 10:30am EDT.
> Update TestNet/MainNet to 2.0.8-stable

- docs/features/indexer.md
The documentation mentioned that it must be base64-encoded. This is only true for the JS SDK and the REST API.
I simplified the code for the other ones and made that clear.
Note: Ideally the examples in https://github.com/algorand/docs/tree/master/examples/indexer should be changed the same way.
Would there be a possibility to make the JS SDK consistent with the other SDK?
> Improvements around note_prefix

- docs/reference/algorand-networks/betanet.md
BetaNet will go live with 2.1.1 at 11:30am 8/7.
> Update betanet.md to 2.1.1-beta

- docs/reference/algorand-networks/betanet.md
BetaNet was updated to 2.1.3-beta on 8/17 at 9:30pm EDT.
> Update BetaNet to 2.1.3-beta

- docs/reference/algorand-networks/mainnet.md
- docs/reference/algorand-networks/testnet.md
Update MainNet and TestNet documentation to 2.1.3-stable. This is scheduled to go live Wednesday 8/19/2020 at 10:30am.
> 2.1.3-stable MainNet/TestNet Update

- docs/reference/algorand-networks/betanet.md
2.1.4-beta was deployed to BetaNet on 8/26.
> Update BetaNet to 2.1.4-beta

- docs/reference/algorand-networks/mainnet.md
- docs/reference/algorand-networks/testnet.md
As of 8/31/2020, the officially supported version is 2.1.4-stable.
> Update TestNet and MainNet to v2.1.4-stable

- docs/features/asc1/stateful/index.md
1. The TEAL examples have placeholders represented with descriptive branch names and commenting. The initial approach for PyTeal was to use descriptive variable names (sometimes) and to return 1. Other considerations would be to return 0 or to return an error. The problem with returning 1 is that it is very permissive and it doesn't emphasize branching examples that well (both branches return 1). 
2. Every snippet is contained in an `approval_program` method and then followed by a write to file. The goal was to make sure that every code snippet compiles for the user (and writing to file also shows which mode to use). But for simple examples is this too much? We need to decide on a good style tenet to follow here.
> Initial draft for adding pyteal code snippets to docs.

- docs/reference/algorand-networks/mainnet.md
- docs/reference/algorand-networks/testnet.md
Update testnet and mainnet to 2.1.5-stable. This is currently live.
> Update to 2.1.5-stable

- docs/run-a-node/setup/install.md
Added a section in Install page to clarify that there is now a separate `algorand-devtools` package and the binaries included in it.  Also, a brief explanation of the expected behaviors regarding the `algorand` package when installing the devtools.
> Added section on installing algorand-devtools package

- docs/reference/algorand-networks/betanet.md
This change is live as of 8:30pm EDT 9/24.
> Update betanet.md to 2.1.6-beta

- requirements.txt
Related Ticket: https://hipo.codebasehq.com/projects/algorand-developer-portal/tickets/320
We should add a fixed version for every package that is in the requirements file to prevent any conflicts with the backend side.
Also, this pull request aims to remove warning about `PymdownxDeprecationWarning` during the building.
> package versions are pinned

- docs/reference/algorand-networks/mainnet.md
- docs/reference/algorand-networks/testnet.md
This is scheduled to go live at 10:30am today (11/4).
> Update mainnet and testnet to v2.2.0-stable

- docs/reference/teal/specification.md
Adding a bank line before two lists, as currently those lists do not appear as lists on the website:
https://developer.algorand.org/docs/reference/teal/specification/#execution-modes
> Minor fix for list

- docs/reference/algorand-networks/betanet.md
Effective as of today 1/19 at 10:30am.
> Update betanet to 2.4.0-beta

- docs/features/accounts/index.md
In many situations (e.g., when using `msgpacktool -d -b32`), base32-encoded public keys are displayed instead of addresses with checksum.
I've added one-liners to the documentation to allow people to easily convert them back and forth.
This may be the wrong place to write those though.
> Adding Python one-liners for addr/pk conversion

- docs/build-apps/connect.md
With the current version of the SDK, `json.dumps(params)` raises the following exception `TypeError: Object of type SuggestedParams is not JSON serializable`.
This is because `param` is an object not a dict.
This issue was found by "user" on Discord.
> Fix json.dump for suggested params in Python

- docs/features/atomic_transfers.md
* Switch to snake style everywhere `signedGroup` -> `signed_group`.
* Simplify grouping by creating directly the array instead of appending.
* Fix inconsistency between `txn_1` and `txn1`.
> Minor style / typos in Py atomic_transfers

- docs/build-apps/connect.md
1. Make clear that the examples are for X-API-Key token, not a general one. Some third-party service such as algoexplorer.io do not require any token.
2. Fix the Java code for `X-API-Key` as it currently does not support general token for authentication.
3. Other minor code improvements
> Fix Java X-API-Key token use and other improvements

- docs/features/asc1/stateless/walkthrough.md
The base64 program adds a newline after 76 characters for legacy reasons and is not needed for this application.
> Add flag to base64

- docs/reference/algorand-networks/betanet.md
This can be published immediately; update took place on 3/20.
> Update betanet to 2.5.2

- docs/reference/algorand-networks/betanet.md
- docs/reference/algorand-networks/mainnet.md
- docs/reference/algorand-networks/testnet.md
Update BetaNet to 2.5.4-beta, and MainNet/TestNet to 2.5.4-stable. This is to go live after 4/13 10:30am.
> Update networks to 2.5.4

- docs/reference/rest-apis/algod/v2.md
the - seems to not be rendered correctly on the developer.algorand.org site, the lists that are displayed correctly have an asterisk rather than a -.  I did not check to see if this appeared anywhere else
> Maybe fix list display on dev site

- docs/reference/sdks/index.md
* Fix outdated links
* Include a link to the new JavaScript reference documentation website
* Change minified library instructions to use a CDN to remain consistent with the JavaScript SDK's README.md
> Update information in the JavaScript SDK overview

- docs/features/asa.md
Updated description of what parameters could be changed after asset creation.
The description repeated freeze twice, when clawback was intended.
> Replaced duplicate w/ correct type in asa.md

- docs/features/asa.md
- docs/reference/algorand-networks/betanet.md
- docs/reference/payment_prompts.md
- docs/reference/sdks/index.md
- docs/run-a-node/setup/install.md
This PR updates a number of unrelated docs to update version numbers and cleanup wording. The JavaScript SDK documentation is now references the new source repo.
> Add JS SDK Updates and Various Other Docs Updates for Versioning and Cleanup

- docs/features/asc1/stateless/sdks.md
In many places in the docs `let` or `var` are used instead of `const`. In this particular area of the code, author changed `var` and `let` to `const` where applicable. Also, re-organized imports to be consistent with node/js best practices. Lastly, went with a main function running with a promise at the bottom.
> Improve readability of smart contract docs

- docs/build-apps/hello_world.md
https://developer.algorand.org/docs/build-apps/hello_world/
the python SDK example for "construct the transaction" section did not import PaymentTxn from algosdk.future.transaction so PaymentTxn was undefined. 
Changes I made:
- added an import of PaymentTxn from algosdk.future.transaction on the docs/build-apps/hello_world.md file at line 236.
> Python SDK under construct the transaction in "3.Your First Transaction" page missing PaymentTxn import

- docs/community.md
This PR adds a link to a minimalistic vim TEAL plugin that adds syntax highlighting to TEAL v3 scripts.
> Add vim TEAL plugin

- docs/reference/node/relay.md
There is a broken link for "Phonebook" at the bottom of https://developer.algorand.org/docs/reference/node/relay/ that I noticed and I believe this will fix it (tested it with `mkdocs serve`).
> Update broken phonebook link in relay node page

- docs/features/accounts/rekey.md
- docs/features/transactions/index.md
https://developer.algorand.org/docs/features/accounts/rekey/
I made the following changes:
- increased transaction microalgos from 1000 to 100000 to prevent minimum balance problem
- added --out filename for creating unsigned txn for rekeying accountA to multisig address
- TEST: SEND WITH AUTH BC_T1 example code wasn't working. changed code to make signing and submitting a transaction from accountA using goal work.
> fixed multisig trx, increased trx amount, added --out filename, added warning message on close out

- docs/reference/algorand-networks/betanet.md
BetaNet was upgraded to version 2.7.1 today, Tuesday Jun 22, 2021 8:30AM ET (12:30PM UTC).
> Update to 2.7.1 beta

- docs/run-a-node/setup/install.md
As mentioned in #272 the "install a node" section has some inconsistencies over the use of `-d ~/node/data`, `-d data` etc which may cause some confusion. In addition, the Fast Catchup section uses a separate (and, seemingly, unnecessary) data directory `~/node/datafastcatchup` which causes an unknown directory error when followed as-is. This version instructs to add `export $ALGORAND_DATA=~/node/data` to shell config files, and no longer specifies the `-d` argument in commands (other than the updating script). In addition, it adds `~/node` to `PATH` which allows `./goal` to be executed simply as `goal`.
Additionally, a typo `~node` was fixed.
> Install a node: standardized data directory references and goal command syntax

- docs/reference/cli/goal/app/create.md
- docs/reference/rest-apis/algod/v2.md
- docs/reference/rest-apis/indexer.md
- docs/reference/teal/opcodes.md
- docs/reference/teal/specification.md
This PR regenerates documentation from source for both the `go-algorand` and `indexer` repos at their latest versions.
> go-algorand @2.7.1 | indexer @2.5.0

- docs/features/asc1/stateful/index.md
Assuming the intention was to write 'progam' with an 'r' to be 'program'
> Typo in asc1/stateful/index.md

- docs/reference/transactions.md
I've seen a few questions come into the discord about how to opt out of an asset.  This should help when searching the docs with the keywords `opt-out`.
> Mentioning opt-out in the AssetCloseTo field

- docs/features/indexer.md
It is no more true that the indexer DB only takes up a fraction of disk space compared to the actual blockchain data with archival mode on.
See for example https://howbigisalgorand.com/ where indexer for mainnet+testnet+betanet actually takes more space than mainnet+testnet+betanet archival algod.
> Removing sentence saying about the indexer DB size

- docs/run-a-node/setup/install.md
The 2.8.0 release added support for installing on CentOS 8, so instructions were modified to indicate this.
Additionally, user-mode systemd support was removed, so references to it were removed from documentation.
> Update instructions to mention centos 8 and remove systemd user support

- docs/build-apps/setup.md
- docs/features/asc1/stateful/hello_world.md
sandbox renamed the `sandbox copy` command
into `sandbox copyTo`
This commit is meant to propagate the change
to the documentation.
> Update sandbox copy to sandbox copyTo

- docs/reference/algorand-networks/betanet.md
Betanet was updated at 10:30AM ET (2:30PM UTC) today Wed Aug 4.
> Update Betanet to v2.9.0-beta

- docs/reference/algorand-networks/betanet.md
BetaNet was upgraded to version 2.10.1, Thu Aug 26, 2021, 10:30AM ET (2:30PM UTC).  This release does not contain a consensus upgrade.
> Update for 2.10.1-beta

- docs/features/transactions/signatures.md
I'm pretty sure amt=10.000.000 corresponds to 10 ALGO, that would also fit the example(s) in https://developer.algorand.org/docs/features/transactions/#send-5-algos.
> Fix wrong amount in txn description

- docs/reference/algorand-networks/betanet.md
BetaNet upgraded to version 3.0.0 today, Wed Sept 15, 2021 2:30PM ET (6:30PM UTC). This release does contain a consensus upgrade.
> Update Betanet to 3.0.0

- docs/reference/algorand-networks/betanet.md
BetaNet was upgraded to version 3.0.1, Mon Sep 20, 2021, 10:30AM ET (2:30PM UTC).  This release does not contain a consensus upgrade.
> Update betanet.md to v3.0.1-beta

- docs/run-a-node/reference/relay.md
MainNet relays are supposed to use port 4160.
This update makes it clear in the documentation.
Same as #574 but against staging.
This update also switches back to the convention that `goal` is in the PATH and `$ALGORAND_DATA` is specified so `-d data` is not needed.
> Indicate to use port 4160 for MainNet relays

- docs/get-details/algorand-networks/betanet.md
BetaNet was upgraded to version 3.2.2, Mon Dec 13, 2021, 11:30AM ET (4:30PM UTC).  This release does not contain a consensus upgrade.
> Update betanet.md (go-algorand 3.2.2-beta release)

- docs/sdks/python/index.md
This causes a syntax error if the code is ran
> Remove extra parenthesis in Python SDK example

- docs/get-details/algorand-networks/betanet.md
BetaNet was upgraded to version 3.2.3, Tue Dec 28, 2021, 1:30 PM ET (6:30PM UTC).  This release does not contain a consensus upgrade.
> Update betanet to version 3.2.3

- docs/get-started/devenv/index.md
Under “Recommendations”, the shell script has comments that are formatted for JavaScript, not Bash.
This can cause issues if it is copied into the terminal.
> Correct comments in shell script

- docs/get-details/dapps/smart-contracts/frontend/apps.md
Removed the phrase "Smart contracts are also referred to as smart contracts" from the docs.
> Removed unnecessary sentence from docs.

- docs/archive/build-apps/connect.md
Update Golang code examples to reflect API changes
It appears that the version 2 `client` moved the `Header` struct from the `algod` package to the `common` package (github.com/algorand/go-algorand-sdk/client/v2/common).
> Fix Go examples inside "Connect a Node" article

- docs/get-details/algorand-networks/betanet.md
BetaNet updated to version 3.3.0 today, Fri Jan 21, 2022, 10:45 AM EST (3:45 PM UTC). This release does not contain a consensus upgrade.
> Update Betanet to v3.3.0-beta

- docs/get-details/dapps/smart-contracts/ABI/index.md
Optionally proposes these surface-level changes to ABI docs:
* Rename _datatype_ to _data type_ because the repo commonly uses _data type_.
* Add punctuation to several sentences.
If folks prefer to keep as is, then feel welcomed to close the PR.
> Fix typos in ABI docs

- requirements.txt
I've not been able to test backwards compatibility with older versions of Python, 3.9 or below.
> Update requirements for Python 3.10 compatability.

- docs/get-details/dapps/smart-contracts/apps/index.md
Documents clear state program constraints when interacting with inner transactions.
Relates to https://github.com/algorand/go-algorand/pull/3556.
> Document clear state program constraints with inner transactions

- mkdocs.yml
Edit button on the site points to https://github.com/algorand/docs/edit/master/docs/index.md
(Button only seen on official site, not locally with `mkdocs serve`)
Edit button points to https://github.com/algorand/docs/edit/staging/docs/index.md
> Mkdocs config: point edit page button to staging & group top-level sections

- docs/get-details/algorand-networks/betanet.md
BetaNet was upgraded to version 3.4.0, Wed Feb 16, 2022, 10:30AM ET (3:30PM UTC).  This release DOES contain a consensus upgrade.
> go-algorand 3.4.0 beta

- docs/sdks/javascript/index.md
makePaymentTxnWithSuggestedParamsFromObject configuration object is referring to `node` instead of `note` in the **transaction note** property.
> Fix typo on transaction example

- docs/get-details/transactions/index.md
The average block time is 4.5 and mentioned in the sentence above. Also the calculation is wrong with 4.25
> Fix miss type

- docs/rest-apis/algod/v2.md
Fixes a typo observed while reading docs.  Change made via `find docs -type f -exec sed -i '' 's/configureation/configuration/g' {} \;`.
> Fix typo in algod REST API docs

- docs/clis/indexer/daemon.md
The last round of code generation missed this change.
> Fix max resources default.

- docs/get-details/dapps/smart-contracts/apps/index.md
The positioning of "the" was on the wrong side of Global State.
> Typo Correction

- docs/get-details/transactions/transactions.md
When opting in to an asset (Asset Accept Transaction) the `snd` field is required rather than the `asnd` field.
> AssetSender should be Sender for an asset optin

- docs/get-details/transactions/transactions.md
As pointed out by @canbolukbas in #800
> AssetCloseTo cannot be supplied with a clawback transaction

- docs/run-a-node/participate/generate_keys.md
New change defaults the key dilution param to the square root of the part period length.
> Update key dilution description

- docs/get-details/dapps/avm/teal/index.md
Fixed an error in the Teal loop example:
`<=` will pop the counter value, `bnz` will pop the compare value, when the loop runs for a second time, the stack will be empty and yield an underflow error when incrementing the counter.
> Fix Teal loop example

- docs/get-details/algorand-networks/betanet.md
BetaNet was upgraded to version 3.6.2, Tuesday, May 3rd, 2022, 10:30 AM ET (2:30 PM UTC).  This release does not contain a consensus upgrade.
> BetaNet upgraded to version 3.6.2

- scripts/reformat-all-commands.sh
DO NOT MERGE UNTIL https://github.com/algorand/go-algorand/pull/3830 HAS BEEN
When generating the CLI documentation for the Developer Portal it was noticed that tealdbg was missing. So much like goal, kmd, and algokey, I've updated the script to include the tealdbg output.
> Add tealdbg docs

- docs/get-details/algorand-networks/betanet.md
- updates betanet to version `3.7.0`
- we recently released `3.7.0`
> algorand-networks: update betanet version

- docs/get-details/algorand-networks/betanet.md
BetaNet was upgraded to version 3.7.2, Thu June 13, 2022, at 10:30 AM ET (2:30 PM UTC).  This release does not contain a consensus upgrade.
> BetaNet was upgraded to version 3.7.2

- docs/get-details/transactions/payment_prompts.md
This PR proposes to add support for opt-in requests by making the address field optional. 
When the address field is missing, sender's address will be used as the receiver's address.
> Add Opt-in URI scheme to Payment Prompts

- docs/get-details/algorand-networks/betanet.md
- docs/get-details/algorand-networks/mainnet.md
- docs/get-details/algorand-networks/testnet.md
This is approved to publish immediately, as all networks have been upgraded to this version.
> Update networks to v3.8.1

- docs/run-a-node/setup/install.md
we should reference a better maintained `update.sh` script
cc: @algojack
> run-a-node: reference more recent updater script

- docs/run-a-node/setup/install.md
problem with pointing to master branch, is that it hasn't been released yet. Instead pointing to rel/stable, which is what we release.
> Updating updater url

- docs/rest-apis/algod/v2.md
Fixed #731 
Added description for online money and total money on this page: https://github.com/algorand/docs/blob/d75a8da87f6289f5ea111bf2980b8c2236dcfff9/docs/rest-apis/algod/v2.md#L481-L485
> issue #731: description for online money and total money added

- docs/clis/indexer/daemon.md
- docs/clis/indexer/util/block-generator/runner.md
Locally tried out the docs/scripts/reformat-all-commands.sh script to update docs for 2.13.0 release (Wed July 27th, 9:30 AM / 1:30PM UTC).
Please merge to update the docs. I only committed changes related to indexer. It looks like our algod documentation is ahead of rel/stable, so I didn't want to overwrite the algod documentation.
> Update Indexer Docs for 2.13.0 release

- docs/run-a-node/setup/install.md
Mac AMD builds are build on xcode12. I have verified it works on v12.3.1, builds are also off v12.3.1, xcode 13.4.
> Update macos doc

- docs/get-started/dapps/pyteal.md
Describe the error
The output of example.py is outdated. The output is different from the current example.py code.
Link to the page or line
https://developer.algorand.org/docs/get-started/dapps/pyteal/#setup-environment-and-run-tests
Fixed the output code on "build with python" page.
Fixed #828
> example.py output updated to the new codebase

- docs/sdks/go/index.md
- docs/sdks/java/index.md
- docs/sdks/javascript/index.md
- docs/sdks/python/index.md
fixed #693 
Removed reference to Algorand Studio and Algorand VScode extension as they are out of date
> removed reference to Algorand Studio and algorand vscode extension

- docs/run-a-node/setup/install.md
Fixed #350 
Added this note to clarify:
Only the first 3 status (`Catchpoint`, `total accounts`, `accounts processed`) will show right after catchup begins. Status on `total blocks` and `downloaded blocks` will only show after catchup processes the total number of accounts, which takes several minutes.
> added note on catchpoint status

- docs/get-details/transactions/signatures.md
fixed #337 
Python multisig code snippets was missing `account_3` when forming `msig`. Added `account_3`.
> added missing account_3

- docs/sdks/go/index.md
> Correct a typo in the go sdk example walkthrough

- docs/run-a-node/setup/install.md
Adding this note to provide some flexibility to people who want to run nodes. 
Also last update date as recommendations may become out of date.
> Adding a note about AWS EBS gp3 being an option

- docs/get-details/dapps/smart-contracts/frontend/smartsigs.md
- examples/smart_contracts/v2/go/accountDelegation.go
- examples/smart_contracts/v2/go/contractAccount.go
- examples/smart_contracts/v2/go/dryrunDebugging.go
Updates go-algorand-sdk for for the rename of `SignLogicsigTransaction` in v2.0.0.
* Corresponding SDK change:  https://github.com/algorand/go-algorand-sdk/pull/445
* All v2.0.0 breaking changes discussed in https://github.com/algorand/go-algorand-sdk/issues/343 / https://github.com/algorand/go-algorand-sdk/pull/449.
* Changes made mechanically via `find . -type f -exec sed -i "" "s/SignLogicsigTransaction/SignLogicSigTransaction/g" {} \;`.
* PR to remain as a _draft_ until post v2.0.0 release.
> go-algorand-sdk:  Update SignLogicsigTransaction examples for v2.0.0

- docs/get-details/asa.md
- docs/get-details/atc.md
- docs/get-details/atomic_transfers.md
- docs/get-details/dapps/smart-contracts/debugging.md
- docs/get-details/dapps/smart-contracts/frontend/apps.md
- docs/get-details/dapps/smart-contracts/frontend/smartsigs.md
- docs/get-details/encoding.md
- docs/get-details/transactions/offline_transactions.md
- docs/get-details/transactions/signatures.md
- docs/sdks/go/index.md
- examples/assets/v2/go/assetExample.go
- examples/atomic_transfers/v2/go/atomicTransfer.go
- examples/multisig/v2/go/multisig.go
- examples/offline/V2/go/multisigOffline.go
- examples/offline/V2/go/offline.go
- examples/smart_contracts/v2/go/accountDelegation.go
- examples/smart_contracts/v2/go/contractAccount.go
- examples/smart_contracts/v2/go/dryrunDebugging.go
- examples/smart_contracts/v2/go/statefulSmartContracts.go
- examples/start_building/v2/go/yourFirstTransaction.go
Updates go-algorand-sdk for the removal of the `future` package in v2.0.0.
* Corresponding SDK change:  https://github.com/algorand/go-algorand-sdk/pull/454
* All v2.0.0 breaking changes discussed in https://github.com/algorand/go-algorand-sdk/issues/343 / https://github.com/algorand/go-algorand-sdk/pull/449.
> go-algorand-sdk:  Update future package examples for v2.0.0

- docs/archive/build-apps/hello_world.md
- docs/get-details/accounts/create.md
- docs/get-details/accounts/rekey.md
- docs/get-details/dapps/pyteal/index.md
- docs/get-details/dapps/smart-contracts/frontend/smartsigs.md
- docs/get-details/transactions/signatures.md
- docs/sdks/python/index.md
- examples/assets/v2/python/asset_example.py
- examples/atomic_transfers/v2/python/atomic_transfer.py
- examples/multisig/v2/python/multisig_transaction.py
- examples/offline/V2/python/multisig_offline.py
- examples/offline/V2/python/offline.py
- examples/smart_contracts/v2/python/account_delegation.py
- examples/smart_contracts/v2/python/contract_account.py
- examples/smart_contracts/v2/python/dryrun_debugging.py
- examples/smart_contracts/v2/python/stateful_smart_contracts.py
- examples/start_building/v2/python/your_first_transaction.py
Updates py-algorand-sdk examples for the removal for `future` package in v2.0.0.  
* Corresponding SDK change:  https://github.com/algorand/py-algorand-sdk/pull/414.
* All v2.0.0 changes discussed in https://github.com/algorand/py-algorand-sdk/issues/384 / https://github.com/algorand/py-algorand-sdk/pull/415.
The PR makes changes mechanically via `find . -type f -exec sed -i "" "s/algosdk.future/algosdk/g" {} \;`.
> py-algorand-sdk:  Update examples for v2.0.0

- docs/get-details/dapps/smart-contracts/frontend/smartsigs.md
Extends #961 by updating docs for removal of `MakeLogicSigAccountEscrow` in https://github.com/algorand/go-algorand-sdk/pull/458.
Changes made mechanically via `find . -type f -exec sed -i "" 's/crypto.MakeLogicSigAccountEscrow/crypto.MakeLogicSigAccountEscrowChecked/g' {} \;`.
> go-algorand-sdk: Update docs for removal of MakeLogicSigAccountEscrow

- docs/get-details/dapps/smart-contracts/frontend/smartsigs.md
- examples/smart_contracts/v2/javascript/AccountDelegation.js
- examples/smart_contracts/v2/javascript/ContractAccount.js
Extends #961 by providing doc updates corresponding to the removal of `makeLogicSig` in https://github.com/algorand/js-algorand-sdk/pull/718.
Changes made mechanically via `find . -type f -exec sed -i "" 's/algosdk.makeLogicSig/new algosdk.LogicSig/g' {} \;`.
> js-algorand-sdk:  Update makeLogicSig examples

- docs/run-a-node/setup/install.md
The old way of adding a trusted apt key is deprecated and will issue a warning. It also likely will stop working with the next Ubuntu update. Changing the command to be more modern.
> Update debian repository key installation command

- docs/get-details/algorand-networks/mainnet.md
- docs/get-details/algorand-networks/testnet.md
I noticed a comment @barnjamin had on one of the automated PRs.
The automation is looking for `v<version>-stable`. 
I'm replacing the previous version convention `.stable` to `-stable` here. This matches with `betanet.md`.
After this gets merged in, the next automated job should replace the version as expected.
> Use hyphens in testnet.md and mainnet.md

- .github/workflows/pr-generator.yml
- docs/clis/conduit/.pages
- docs/clis/conduit/conduit.md
- docs/clis/conduit/init.md
- docs/clis/conduit/list/.pages
- docs/clis/conduit/list/exporters.md
- docs/clis/conduit/list/importers.md
- docs/clis/conduit/list/list.md
- docs/clis/conduit/list/processors.md
- docs/get-details/conduit/exporters/filewriter.md
- docs/get-details/conduit/exporters/postgresql.md
- docs/get-details/conduit/importers/algod.md
- docs/get-details/conduit/importers/filereader.md
- docs/get-details/conduit/processors/blockevaluator.md
- docs/get-details/conduit/processors/filter.md
- scripts/reformat-all-commands.sh
Adds conduit CLI docs, and additionally generates the docs for conduit plugin configs.
The github workflow is a bit difficult to test. I've validated as much as I can locally that the scripts all work as intended, and I've tried to run the workflow locally with [act](https://github.com/nektos/act).
Sample plugin config page:
> Add conduit

- docs/get-details/transactions/index.md
might have fallen through the cracks during the state proof update
> bumped number of transaction types from 6 to 7

- docs/get-details/parameter_tables.md
`Per Box created` is `2500` or `0.0025` according to the referenced doc & implementation.
> Fix value for Per Box created

- scripts/README.md
- scripts/config_json_gen/main.go
- scripts/config_json_gen/template.tmpl
localTemplate.go needs to be modified before this tool will be really useful. The documentation is not all complete and some is completely missing. The tool attempts to write warnings to stdout, currently it prints the following:
```
missing comment for type: NetAddress
missing comment for type: MaxConnectionsPerIP
missing comment for type: TLSKeyFile
missing comment for type: CadaverDirectory
missing comment for type: RestWriteTimeoutSeconds
missing comment for type: SuggestedFeeBlockHistory
```
See the README for more information.
> Tool to generate node config markdown documentation from go-algorand source.

- docs/run-a-node/setup/install.md
I originally copy/pasted some details from the DockerHub page, but if that gets updated I didn't want out-of-date info on the portal so just removed everything and left the link.
> Include DockerHub link in node setup page

- docs/rest-apis/algod.md
- docs/rest-apis/indexer.md
- docs/run-a-node/setup/node-troubleshooting.md
- scripts/reformat-all-commands.sh
This PR updates the docs generated from source base on:
- go-algorand:v3.15.1-stable
- indexer:develop
This also modifies the generation script to output the `algod` API docs to the proper location.
> update docs from source

- docs/get-details/technical_faq.md
Clarified meaning of `TransactionInLedgerError` error. It actually means the txn is either in a pool (pendgin block eval) or in ledger.
> faq: update `transaction already in ledger` error

- docs/get-details/encoding.md
- docs/get-details/technical_faq.md
If my math is correct, the `base32` encoding of the underlying `32+4` bytes of the private key results in 58 symbols accounting for padding.
`ceil((32+4)*8/5) = ceil(57,6) = 58`
The encoding shouldn't change the underlying number of bytes which is always 36 so I find that description confusing.
I propose we should use `symbols` or `characters` in the docs to describe the length of the encoding in `base32`
> Fixing 58 bytes encoding.

- .github/workflows/release-checker.yml
Indexer's default branch is now `main`. This script was erroring because `master` no longer existed.
N/A - see if the checker succeeds now.
> Bug Fix: release checker is pointing to incorrect indexer branch

- docs/get-details/useful_resources.md
this PR adds the Bootcamps repo to the useful resources page
> add bootcamps

- scripts/reformat-all-commands.sh
The latest version isn't always the current mainnet version, so instead use vFuture - 1 as mainnet, and insert a warning into the vFuture opcode docs about potential changes.
> Use vFuture version from go-algorand

- docs/get-details/dapps/smart-contracts/guidelines.md
Adding some example code to write smart signatures that check against the network they are being run on. This is an initial guess as the PR still needs to make its way to prod, but it should be close.
Related PR: https://github.com/algorand/go-algorand/pull/5858
> Adding code example for smart signatures to check genesis hash.

- .github/workflows/pr-generator.yml
- .github/workflows/release-checker.yml
Should now pickup 'v' prefixed tags, and use GitHub to download the binaries
> Fix Indexer version within GitHub Actions

- .github/workflows/pr-generator.yml
Since Indexer 3 a 'v' is prefixed at the start
> Fix tag ref for github actions

- docs/get-details/dapps/writing-contracts/.pages
- docs/get-details/dapps/writing-contracts/beaker.md
- docs/get-details/dapps/writing-contracts/pyteal.md
- docs/get-details/dapps/writing-contracts/python.md
After numerous complications ingesting the docs into the developer portal, we'll link to the original docs for now and work on a better automated solution after launch.
Also added a note to both PyTeal and Beaker pages.
> Link to Algorand Python GitHub docs for now

- docs/get-started/algokit.md
- Removed Quickstart videos until further review
- Minor wording change (~~`Beaker`~~)
> Quickstart Updates

- .go-algorand-stable.version
- docs/clis/algokey/generate.md
- docs/clis/goal/account/account.md
- docs/clis/goal/account/assetdetails.md
- docs/clis/goal/account/info.md
- docs/get-details/algorand-networks/mainnet.md
- docs/get-details/algorand-networks/testnet.md
- docs/get-started/algokit.md
- docs/rest-apis/algod.md
> staging => master

- docs/get-started/basics/why_algorand.md
This PR makes minor text changes to update the chain's throughput/TPS number, which has increased as a result of block times being reduced.
> Docs: Update TPS numbers

- .github/workflows/pr-generator.yml
This workflow creates a new PR when a new go-algorand or indexer release is made. It automatically updates the docs based on the latest REST API, Configuration values, or CLI changes. Probably other changes too. This PR is adding additional reviewers.
> Add new reviewers

- .github/workflows/pr-generator.yml
The pr-generator action is hitting the following error.
> /home/runner/work/docs/docs/indexer/go.mod:5: unknown directive: toolchain
This PR attempts to fix it by bumping the version to 1.21.10
> Fix pr-generator workflow

- .github/workflows/pr-generator.yml
> Error: Reviews may only be requested from collaborators. One or more of the users or teams you specified is not a collaborator of the algorandfoundation/docs repository.
> The pr-generator workflow is failing as these users are non-contributors

- docs/get-started/basics/why_algorand.md
discrepancy in max tps of 9000 which is fixed to 10,000
> fixed max tps

- docs/get-started/algokit.md
The command  old command triggers error (Command not found), and following the CLI help, this one is the correct one
> Fixed correct deploy command
