algorandfoundation/docs

- docs/.pages
- docs/about.md
- docs/features/asa.md
Added about page and minor updates to assets page.
> Periodic merge of staging into master

- docs/reference/cli/.pages
- docs/reference/cli/diagcfg/.pages
- docs/reference/cli/diagcfg/diagcfg.md
- docs/reference/cli/diagcfg/metric.md
- docs/reference/cli/diagcfg/telemetry.md
- docs/reference/node/.pages
- docs/reference/node/telemetry-config.md
Added documentation for telemetry configuration behavior and the diagcfg CLI.
> added docs for telemetry config and diagcfg CLI

- docs/features/indexer.md
pr for note field searching doc improvements
> Note Field Searching Improvements

- docs/build-apps/setup.md
Fixes broken link to community/#sdks
> fixup community/#sdks ref

- docs/features/asc1/stateful/hello_world.md
fixup external state storage, add primer
> Update Stateful Hello World

- examples/atomic_transfers/v2/javascript/atomicTransfer.js
> Update atomic group js example

- docs/reference/algorand-networks/mainnet.md
- docs/reference/algorand-networks/testnet.md
This is effective immediately.
> Update TestNet and MainNet to 2.0.9-stable

- docs/features/asc1/stateless/sdks.md
to modify config.json for "EnableDeveloperAPI": true
> Updated sdks.md to include instructions in the compile section 

- docs/features/accounts/rekey.md
Replace `goal account dump --account` with `goal account dump --address`
> fixup dump --address

- docs/build-apps/apps.md
- docs/features/accounts/rekey.md
- docs/features/asc1/stateful/.pages
- docs/reference/algorand-networks/mainnet.md
- docs/reference/algorand-networks/testnet.md
MainNet Upgrade complete. This removes 🔷 from feature pages and updates network pages.
> Remove BetaNet diamond and language.

- docs/reference/rest-apis/algod/v2.md
- docs/reference/teal/opcodes.md
- docs/reference/teal/specification.md
- scripts/reformat-all-commands.sh
This PR updates the reference documentation from source from go-algorand:master and indexer:develop.
> Update Reference Docs from Source

- docs/features/asc1/stateful/.pages
- docs/features/asc1/stateful/sdks.md
- examples/smart_contracts/v2/go/statefulSmartContracts.go
- examples/smart_contracts/v2/java/StatefulSmartContract.java
- examples/smart_contracts/v2/javascript/statefulSmartContracts.js
- examples/smart_contracts/v2/python/stateful_smart_contracts.py
This PR adds a walkthrough of an example stateful smart contract throughout its lifecycle.
> Stateful Smart Contracts - Using the SDKs

- docs/features/asc1/stateless/sdks.md
- examples/smart_contracts/v2/python/account_delegation.py
- examples/smart_contracts/v2/python/compile_teal.py
- examples/smart_contracts/v2/python/contract_account.py
- examples/smart_contracts/v2/python/dryrun_debugging.py
Reduced read from file function to one line. Added missing imports. Removed unnecessary imports.
> Simplifications to Python code.

- docs/reference/rest-apis/algod/v2.md
- docs/reference/rest-apis/indexer.md
This PR updates the reference documentation from source from go-algorand:master and indexer:develop.
> Update docs from Source

- docs/reference/algorand-networks/mainnet.md
- docs/reference/algorand-networks/testnet.md
This is scheduled to go live at 9/25 12:30pm EDT.
> 2.1.6-stable Update

- docs/features/asc1/stateful/sdks.md
Add new line to allow proper content rendering
> fixup md formatting

- docs/features/asc1/stateful/sdks.md
- requirements.txt
Simple fixup and clarifications
> fixup formatting and clarify package versions

- docs/run-a-node/setup/install.md
> Install docs change

- docs/reference/algorand-networks/betanet.md
Update version of latest released betanet version.
> betanet 2.2.0-beta release

- docs/reference/algorand-networks/betanet.md
- docs/reference/algorand-networks/mainnet.md
- docs/reference/algorand-networks/testnet.md
Update betanet to 2.3.0-beta and 2.3.0-stable.
> 2.3.0 network update

- docs/run-a-node/participate/generate_keys.md
See https://github.com/algorand/docs/pull/275
> Add note about permissions on Debian/Ubuntu in generate_keys.md

- docs/community.md
* Added a new category for "Monitoring & Analytics"
* Added a description of AlertHub to the new category
> Add AlertHub description to community.md

- docs/build-apps/hello_world.md
- examples/start_building/v2/go/yourFirstTransaction.go
- examples/start_building/v2/java/YourFirstTransaction.java
- examples/start_building/v2/javascript/yourFirstTransaction.js
- examples/start_building/v2/python/your_first_transaction.py
WaitForConfirmation updated for all SDKs and doc on your-first-transaction
> Waitforconfirmation updated

- docs/build-apps/hello_world.md
- examples/start_building/v2/go/yourFirstTransaction.go
- examples/start_building/v2/java/YourFirstTransaction.java
- examples/start_building/v2/javascript/yourFirstTransaction.js
- examples/start_building/v2/python/your_first_transaction.py
updated getting started for waitforconfirmation
> WaitForConfirmation Function update

- docs/reference/algorand-networks/mainnet.md
- docs/reference/algorand-networks/testnet.md
This is effective immediately.
> Updates for 2.4.1-stable release

- docs/reference/sdks/index.md
Also updated run in postman buttons
> Updated kmd swagger link curl command

- docs/run-a-node/setup/install.md
This is a feature request from the community: https://github.com/algorand/go-algorand/issues/1490 and should be merged at the same time as the code on that ticket.
Sorry about the noise from removing the whitespace.
> Added systemd docs

- docs/reference/sdks/index.md
> update java sdk version

- docs/reference/sdks/index.md
> Updated REST API for Indexer and Algod API Run in postman

- docs/community.md
See https://developer.algorand.org/docs/community/#algorand-ides: the title is included in the table.
> Fixing minor formatting issue

- docs/community.md
> minor formatting fix

- docs/build-apps/connect.md
- docs/reference/node/artifacts.md
updates to master for java example and node artifacts
> Minor updates to docs and Java example

- docs/build-apps/connect.md
Earlier interaction you set it here:  const algodClient = new algosdk.Algodv2(algodToken, algodServer, algodPort) with a capital C
> Capitalization fix

- docs/run-a-node/participate/generate_keys.md
The note was not formatted properly.
> Fixing style

- docs/run-a-node/setup/install.md
Improper note styling, so the note was not displayed correctly.
> Fix styling

- examples/atomic_transfers/v2/python/atomic_transfer.py
See #302 
+ add two line breaks between functions to follow PEP8.
Same as #303 but comparing with staging instead of master
> Minor style fixes

- docs/features/asc1/teal/pyteal.md
One assertion `is_one_tx` is missing in the `And` basket below
> Fix bugs in pyteal.md

- docs/features/asc1/stateful/sdks.md
> Remove superfluous line in Python code

- docs/features/asa.md
- docs/features/asc1/stateless/sdks.md
- docs/features/asc1/stateless/walkthrough.md
- docs/features/asc1/teal/pyteal.md
- docs/features/transactions/signatures.md
- docs/reference/node/config.md
Fixed some minor typos in the documentation.
> Fixing small typos

- docs/reference/algorand-networks/betanet.md
- docs/reference/algorand-networks/mainnet.md
- docs/reference/algorand-networks/testnet.md
Update network versions for latest release
> go-algorand 2.5.5 network update

- docs/features/accounts/create.md
- examples/accounts/v2/go/createNewAccounts.go
> Updates to Create Accounts

- docs/reference/.pages
- docs/reference/index.md
- docs/reference/payment-prompts.md
This PR adds documentation for the Payments Prompts URI specification.
> add payment prompts

- docs/reference/payment_prompts.md
This fixes some typos pointed out by users in our discord.
> Fix typos in payment prompt spec

- docs/features/asc1/teal/pyteal.md
Update PyTEAL example to version 3
and make it secure (`RekeyTo` check was missins).
> Update PyTEAL example to version3

- docs/features/asc1/stateful/index.md
Explanation of how to read the output of `goal app read`
See https://forum.algorand.org/t/interpreting-goal-app-read-response/2711/2?u=fabrice.
> Add how to read output of `goal app read`

- docs/features/asc1/stateful/index.md
Suggesting some improvements and additions in order to clear things a bit when handling state.
In case this is approved, I guess it's best if changes apply also in [TEAL_opcodes.md in go-algorand repo](https://github.com/algorand/go-algorand/blob/master/data/transactions/logic/TEAL_opcodes.md)
> suggested minor improvements and additions for state operations

- docs/build-apps/hello_world.md
- examples/start_building/v2/javascript/yourFirstTransaction.js
* Fix a capitalization typo
* Move the documentation in single place and follow JSDoc
* Only throw error instead of strings
* Use const wherever possible
> Improve the JS function `waitForConfirmation`

- docs/build-apps/hello_world.md
- docs/features/asc1/stateful/index.md
- docs/features/atomic_transfers.md
- examples/start_building/v2/javascript/yourFirstTransaction.js
This PR adds cleans up the docs for various typos and improved readability.
> fixup: various minor enhancements

- docs/build-apps/connect.md
- docs/build-apps/hello_world.md
- docs/features/atomic_transfers.md
- docs/reference/algorand-networks/betanet.md
- docs/reference/algorand-networks/testnet.md
What did I change as part of issue #394 :
- Remove `...` dots in code snippets as I believe it's not necessary. Also, when copying the code snippet, you automatically copy the dots as well.
- Change `var` to `const` or `let` for JS snippets
- Better alignment for snippets and spacing
- JS snippet contained a Java code snippet to `private String printBalance` -> moved to the Java code example 
- There's no Google sign-in for re-captcha of faucet
> Add fixes tutorials hello-world and atomic-transfers - Issue #394

- docs/community.md
Adding HowBigIsAlgorand.com to the list of community projects :)!
> feat: added HowBigIsAlgorand to the list

- docs/build-apps/hello_world.md
> Revert "Python SDK under construct the transaction in "3.Your First Transaction" page missing PaymentTxn import"

- examples/assets/v2/javascript/AssetExample.js
> Revert "Update AssetExample.js"

- docs/features/asc1/stateless/walkthrough.md
Contract Account ASA Opt-In is a pretty common operation in several use-cases based on Stateless ASC1. Here I provide an example of custom ASA Opt-In TEAL logic.
> Contract Account ASA Opt-In

- docs/features/asc1/stateful/index.md
Fixing formatting (currently the list does not appear correctly: https://developer.algorand.org/docs/features/asc1/stateful/?query=tt#reading-a-smart-contracts-state)
> Fix formatting in ASC1

- docs/run-a-node/setup/install.md
Adding a link on how to switch networks
> Fix install.md

- docs/build-apps/setup.md
- docs/features/asc1/stateful/hello_world.md
People on forum and Discord regularly have issues using sandbox with external files.
This PR is meant to provide some additional guidance.
See https://forum.algorand.org/t/where-does-sandbox-goal-clerk-compile-execute/3571/2?u=fabrice
> Add documentation on how to use sandbox copy

- docs/reference/transactions.md
- Adds `ExtraProgramPages`
- corrects type for Approval & Clear programs
- fixup typos
> Transaction reference updates for 2.7.1

- docs/sdks/python/index.md
- mkdocs.yml
added the getting started with python page.
> avm-staging getting started with python updated

- docs/reference/algorand-networks/betanet.md
Betanet was updated on Wednesday Jul 21 10:30am ET
> Update BetaNet 2.8.0

- docs/reference/algorand-networks/mainnet.md
- docs/reference/algorand-networks/testnet.md
Release 2.8.0 was updated on Wednesday 7/28.
> Dev/stable 2.8.0

- docs/reference/algorand-networks/betanet.md
Update betanet version to 2.9.1
> Update betanet version

- docs/reference/algorand-networks/betanet.md
> Update to 2.10.0 beta

- docs/reference/algorand-networks/betanet.md
- docs/reference/algorand-networks/mainnet.md
- docs/reference/algorand-networks/testnet.md
> Updates for released versions

- docs/features/walletconnect.md
Add an info box for developers to watch for new releases and update.
> add walletconnect-monorepo

- docs/run-a-node/setup/install.md
This is in response to https://forum.algorand.org/t/installation-problems-on-ubuntu-20-04/4053
> Make clearer Debian packages work for Ubuntu

- docs/reference/parameter_tables.md
Including the following tables:
```
Minimum balance
Minimum balance for smart contract
Transaction fee
Others
ASA constraints
Stateless smart contract constraints
Stateful smart contract constraints
```
> adding a page with frequently used/viewed chain parameters and constraints

- docs/reference/.pages
- docs/reference/index.md
- fixup nodes 
- add parameters table
> fixup reference index

- docs/reference/algorand-networks/betanet.md
> Update Betanet to 3.0.0

- docs/sdks/javascript/index.md
info
video link alignment
bullet list
> Formatting fixes on javascript getting started

- docs/get-details/index.md
- docs/get-details/parameter_tables.md
modified index for get details
> get details index update

- docs/get-started/integration/assets.md
- docs/get-started/tokenization/ft.md
- docs/get-started/tokenization/nft.md
- docs/get-started/tokenization/security_token.md
> Add Python tokenization code snippets

- docs/get-started/integration/assets.md
- docs/get-started/tokenization/ft.md
- docs/get-started/tokenization/nft.md
- docs/get-started/tokenization/security_token.md
- minor fixups for code snippets and links
> Cleanup Integrations & Tokenization

- docs/rest-apis/algod/v2.md
- Add correct key for `global-state0-schema`
- Add information about `tt` value for storage and change order for readability
> Schema fixes TEAL

- docs/get-started/dapps/pyteal.md
> Pyteal page enhancement

- docs/get-details/walletconnect/index.md
> fix txn signing map issue

- docs/get-details/walletconnect/index.md
- docs/get-details/walletconnect/walletconnect-schema.md
Before
After (IDE Preview)
Other changes are self-explanatory.
> Fix typo and format

- docs/get-details/dapps/pyteal/index.md
SC contract would not run w/out errors without changing to version 5.  Went ahead and updated Smart Sig to v5 also but it wasn't having any issues.
> Updated Teal Ver to 5 so SC runs w/out errors

- examples/smart_contracts/v2/javascript/statefulSmartContracts.js
error on old Line 553: TypeError:
The "value" argument must not be of type number. Received type number
Should I update the `smart-contracts.zip` file as well?
> fix(typo): fix Buffer type error; add comment

- docs/get-details/encoding.md
Adding more/better examples for encoding and decoding transaction objects
> add encoding/decoding for transaction objects

- CONTRIBUTING.md
Updated link to related issue template.
> Corrected issue template link.

- docs/sdks/go/index.md
- docs/sdks/java/index.md
The faucet now sends 5 Algo, so reduced the amount to send so people don't get an overspend error. Also removed a wild 'The'.
> Two small updates.

- docs/get-started/dapps/reach.md
closed space in link and removed a double space.
> docs: fixed broken hyperlink

- docs/get-details/accounts/create.md
- docs/run-a-node/participate/online.md
- docs/run-a-node/participate/renew.md
Fixes typos and stale links I encountered during node setup.
> Fix typos and stale links

- docs/get-details/dapps/smart-contracts/smartsigs/walkthrough.md
Optionally proposes minor rephrasing to smart signatures docs to improve reader clarity. 
I created the PR because I misinterpreted the document's intent on first read.  If folks don't feel the PR is worth pursuing, then feel welcomed to close the PR.
> Rephrase reference to example smart signature TEAL compilation

- docs/get-details/dapps/avm/teal/index.md
> Fix another typo in index.md

- docs/get-details/atomic_transfers.md
- docs/get-details/transactions/index.md
- docs/sdks/go/index.md
- docs/sdks/javascript/index.md
- docs/sdks/python/index.md
> Updates to fee docs and JS docs 

- docs/get-details/dapps/smart-contracts/apps/index.md
- docs/get-details/transactions/index.md
Fixes typos and optionally suggestions rephrasing to smart contract docs.
As part of my onboarding, I'm closely reading the dev docs.  Subjectively, I left rephrasing suggestions where I felt the reader can more easily follow along.   Feel welcomed to reject any (or all) of these suggestions.
> Fix typos and suggest rephrasings in smart contracts docs

- docs/get-started/dapps/reach.md
also needs this pr (https://github.com/algorand/reach-auction/pull/1)
> docs - new version requires new stdlib import

- docs/get-details/dapps/pyteal/index.md
I wanted to take a pass at the PyTeal documentation to do a few things:
- add some notes about a mental model
- strip it down to PyTeal specific information to make it less verbose (let smart contract info live in smart contract page)
- slight refactor to logic
> PyTeal docs updates

- docs/get-details/dapps/pyteal/index.md
- docs/get-details/dapps/smart-contracts/frontend/apps.md
Further to Fabrice's PR #726 I've changed another instance of its use, and also attempted to update the other languages to read global state data without involving the creators address.
> Read global state changes

- docs/get-started/devenv/index.md
This has been requested by Michiel Mulders (Algorand Foundation). The provider will launch within a week. Can you please merge? Thanks!
> Adding Bloq as API provider

- docs/get-started/dapps/reach.md
- Removes a repeated sentence
- Removes an extra comma
> Simplifies wording in Backend intro

- docs/clis/goal/account/account.md
- docs/clis/goal/account/listpartkeys.md
- docs/clis/goal/account/partkeyinfo.md
- docs/clis/goal/app/app.md
- docs/clis/goal/app/call.md
- docs/clis/goal/app/clear.md
- docs/clis/goal/app/closeout.md
- docs/clis/goal/app/delete.md
- docs/clis/goal/app/info.md
- docs/clis/goal/app/interact/execute.md
- docs/clis/goal/app/interact/interact.md
- docs/clis/goal/app/interact/query.md
- docs/clis/goal/app/method.md
- docs/clis/goal/app/optin.md
- docs/clis/goal/app/read.md
- docs/clis/goal/app/update.md
- docs/clis/goal/asset/config.md
- docs/clis/goal/asset/create.md
- docs/clis/goal/asset/destroy.md
- docs/clis/goal/asset/freeze.md
- docs/clis/goal/asset/send.md
- docs/clis/goal/clerk/dryrun.md
- docs/clis/goal/clerk/send.md
- docs/get-details/dapps/avm/teal/opcodes.md
- docs/get-details/dapps/avm/teal/specification.md
- docs/rest-apis/algod/v2.md
- docs/rest-apis/indexer.md
This PR updates docs from source based on:
- https://github.com/algorand/go-algorand/releases/tag/v3.4.1-beta
- https://github.com/algorand/indexer/releases/tag/2.8.4
> Docs for Releases 3.4.1 & 2.8.4

- docs/get-details/algorand-networks/betanet.md
Update betanet network to 3.4.2-beta in documentation.
> Update betanet to 3.4.2-beta

- docs/sdks/python/index.md
The complete example was missing a variable (it was referenced in another code snippet above though).
> Add Missing "amount" in Python Complete Example

- docs/get-details/algorand-networks/betanet.md
> Update betanet.md for version 3.5.0

- docs/clis/goal/account/info.md
- docs/clis/indexer/daemon.md
- docs/rest-apis/algod/v2.md
- docs/rest-apis/indexer.md
There were some other changes, but I don't know if they were expected.
This includes just the changes I was expecting to see.
> Regenerate docs for unlimited assets release.

- docs/rest-apis/indexer.md
This PR updates docs from source for indexer 2.9.0
> update docs for indexer 2.9.0

- docs/get-details/atc.md
Fix and add java information for atc.md details
- BasicAccountTransactionSigner to TxnSigner
- Add java code for ABI call method
> Update atc.md fix and add java code for abi call method

- docs/get-details/transactions/transactions.md
Should close https://github.com/algorand/go-algorand/issues/3959
Do we not have this auto-gen'd yet?
> add stateproofpk to transaction field docs

- docs/get-details/algorand-networks/betanet.md
this updates betanet details to display the most recent version (3.7.1-beta)
> betanet: update version to 3.7.1-beta

- docs/get-details/accounts/index.md
Include application-related changes and explicitly indicate that destroying/opting out an asset/application reduces the minimum balance.
> Clarify minimum balance text

- docs/get-details/indexer.md
Elaixzar#6238 asked about it on discord
> Add missing tx type "appl" to text

- docs/get-started/integration/assets.md
Fixed grammar error on this page: https://developer.algorand.org/docs/get-started/integration/assets/
> fixed grammar error

- docs/get-details/dapps/smart-contracts/index.md
Fixed #744 
Erased cut off sentence on https://github.com/algorand/docs/blob/staging/docs/get-details/dapps/smart-contracts/index.md?plain=1#L14
> issue #744: fixed cut off sentence

- docs/run-a-node/reference/config.md
Fixed the description about publicAddress on this page https://github.com/algorand/docs/blob/staging/docs/run-a-node/reference/config.md
Fixed #842
> issue #842: publicAddress config.md file fixed

- docs/run-a-node/reference/config.md
Fixed #840 
reconnectTime value fixed to nanoseconds
> Issue #840 reconnectTime value fixed

- docs/get-started/tokenization/nft.md
Fixed #631 
Reference to step by step video guide on NFT creation deleted as there are no video guide on it.
> erased video guide reference

- examples/indexer/javascript/AccountInfo.js
- examples/indexer/javascript/AccountInfoBlock.js
- examples/indexer/javascript/AccountsAssetID.js
- examples/indexer/javascript/AccountsAssetIDMinBalance.js
- examples/indexer/javascript/AssetsBalances.js
- examples/indexer/javascript/AssetsBalancesMinBalance.js
- examples/indexer/javascript/BlockInfo.js
- examples/indexer/javascript/SearchAssets.js
- examples/indexer/javascript/SearchAssetsName.js
- examples/indexer/javascript/SearchAssetsTransactionsRole.js
- examples/indexer/javascript/SearchTransactionsLimit.js
- examples/indexer/javascript/SearchTransactionsMinAmount.js
- examples/indexer/javascript/SearchTransactionsNote.js
- examples/indexer/javascript/SearchTransactionsPaging.js
- examples/indexer/javascript/SearchTxAddressAsset.js
- examples/indexer/javascript/SearchTxAddressBlock.js
- examples/indexer/javascript/SearchTxAddressBlockRange.js
- examples/indexer/javascript/SearchTxAddressTime.js
- examples/indexer/javascript/SearchTxAddressTxId.js
- examples/indexer/javascript/SearchTxAddresssigtype.js
- examples/indexer/javascript/SearchTxAddresstxntype.js
Changed `let` to `const` for all indexer examples where they are appropriate.
Fixed #273
> changed let to const for fixed variables

- examples/smart_contracts/v2/javascript/dryrunDebugging.js
> updated outdated js dryrunDebugging code

- docs/get-details/dapps/smart-contracts/frontend/apps.md
- examples/smart_contracts/v2/javascript/statefulSmartContracts.js
- examples/smart_contracts/v2/python/stateful_smart_contracts.py
changed optin function argument `index` to `app_id` for more clarity.
Fixed #340
> change argument index to app_id for clarity

- docs/get-started/dapps/reach.md
ParticipationClass is deprecated.
> Replaced ParticipationClass with api

- docs/get-details/dapps/avm/teal/specification.md
- docs/get-details/dapps/smart-contracts/apps/index.md
Extends #877 to catch additional TEAL vs AVM/program references.
> Tweak verbiage in #877

- .github/workflows/release-checker.yml
documentation: https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow
> Update release-checker.yml github action

- docs/run-a-node/setup/install.md
for https://github.com/algorand/go-algorand/pull/4367
> Fix permissions on update.sh

- docs/get-started/basics/why_algorand.md
It's the same, just with a leading zero. Had someone misinterpret it as 0.01
> readability

- docs/sdks/go/index.md
> Add a required context parameter in the go sdk example walkthrough code

- docs/run-a-node/participate/generate_keys.md
- docs/run-a-node/participate/renew.md
> Key registration fixes

- docs/get-details/dapps/smart-contracts/ABI/index.md
update method pseudo-opcode return value to match example method signature.
> fixup method call

- docs/run-a-node/operations/switch_networks.md
- docs/run-a-node/setup/.pages
- docs/run-a-node/setup/install.md
- docs/run-a-node/setup/node-troubleshooting.md
This PR adds a node troubleshooting document helping user fix common issues with nodes.
Also contain a few minor fixes.
> Node troubleshooting

- docs/clis/goal/clerk/dryrun-remote.md
- docs/clis/goal/clerk/dryrun.md
- docs/clis/tealdbg/tealdbg.md
- docs/get-details/dapps/smart-contracts/debugging.md
this commit fixes warnings I inadvertently removed in my previous algod v1 [commit](https://github.com/algorand/docs/commit/4139378259a301221740beb5aaa34aaa4e451c53)
> fixup dryrun and tealdbg

- docs/run-a-node/setup/indexer.md
> removing frozen help text, adding data-dir

- .github/workflows/pr-generator.yml
(we took that part out by accident, adding it back in)
> Adding back automatic PR creation

- docs/get-details/dapps/avm/teal/jsonspec.md
- scripts/reformat-all-commands.sh
This PR modifies the build script:
- revert #CONDUIT section (will refactor in future PR)
- add jsonspec to #TEAL section 
jsonspec.md is added
> add jsonspec.md

- docs/get-details/parameter_tables.md
> Adding box constraints to param table

- examples/assets/v2/python/asset_example.py
> fix renamed function

- docs/get-details/indexer.md
> fix indexer examples in python tabs

- scripts/import_examples.py
Added TEAL too as I'm starting to add the examples.
> Added file extension to ExampleSource

- scripts/import_examples.py
Save us fighting over changes when working on different languages.
> Uncomment all ExampleSource but check if directory exists

- docs/get-details/dapps/smart-contracts/apps/index.md
> Correct typo

- docs/get-details/dapps/smart-contracts/guidelines.md
> Fixing typos in guidelines

- docs/get-details/accounts/create.md
- docs/get-details/accounts/rekey.md
- docs/get-details/asa.md
- docs/get-details/atc.md
- docs/get-details/atomic_transfers.md
- docs/get-details/dapps/smart-contracts/apps/index.md
- docs/get-details/dapps/smart-contracts/debugging.md
- docs/get-details/dapps/smart-contracts/frontend/apps.md
- docs/get-details/dapps/smart-contracts/frontend/smartsigs.md
- docs/get-details/dapps/smart-contracts/guidelines.md
- docs/get-details/encoding.md
- docs/get-details/indexer.md
- docs/get-details/transactions/index.md
- docs/get-details/transactions/offline_transactions.md
- docs/get-details/transactions/signatures.md
- scripts/import_examples.py
Missing the following
- Missing TRANSACTION_KEYREG_OFFLINE_CREATE in JSSDK examples (in ../docs/run-a-node/participate/offline.md:34)
- JSSDK doesn't support this
- Missing TRANSACTION_KEYREG_ONLINE_CREATE in JSSDK examples (in ../docs/run-a-node/participate/online.md:16)
- JSSDK doesn't support this
- Missing SP_MIN_FEE in JSSDK examples (in ../docs/get-details/dapps/smart-contracts/guidelines.md:91)
- JSSDK doesn't support this
- Missing CODEC_BLOCK in JSSDK examples (in ../docs/get-details/encoding.md:369)
- Unsure of what we want here
> JS doc examples

- docs/sdks/go/index.md
- docs/sdks/java/index.md
- docs/sdks/javascript/index.md
- docs/sdks/python/index.md
Make all the first txn walk throughs match and specify sandbox starting with dev mode config instead of testnet
> make all the first transaction examples match

- docs/get-details/parameter_tables.md
- fixed the typo
- added box storage to the list
> fixed typo on and added box storage to MaxAppTotalTxnReferences

- docs/clis/conduit/init.md
- docs/get-details/conduit/Configuration.md
- docs/get-details/conduit/Development.md
- docs/get-details/conduit/Docker.md
- docs/get-details/conduit/GettingStarted.md
- docs/get-details/conduit/plugins/algod.md
- docs/get-details/conduit/tutorials/FilterDeepDive.md
- docs/get-details/conduit/tutorials/IndexerMigration.md
- docs/get-details/conduit/tutorials/IndexerWriter.md
- docs/get-details/conduit/tutorials/WritingBlocksToFile.md
Regenerate CLI documentation and update hand written documentation.
> Conduit Documentation Update

- docs/get-details/accounts/create.md
- docs/get-details/accounts/index.md
- docs/get-details/dapps/smart-contracts/apps/index.md
- docs/get-details/encoding.md
- docs/get-details/transactions/offline_transactions.md
- docs/sdks/go/index.md
Adds details and examples to close #1105
> Application account details

- docs/run-a-node/setup/node-troubleshooting.md
> fixed broken link to dappflow node manager

- docs/get-details/dapps/smart-contracts/apps/txs.md
> Revert "minor ref change"

- docs/get-details/accounts/create.md
attempting to embed youtube video content within page
> test direct YT URL

- docs/get-details/accounts/create.md
> fix up syntax

- docs/get-details/accounts/create.md
> fix up syntax, again

- docs/get-details/conduit.md
this PR:
- changes the "built binaries" link to GitHub Releases from README
- fixup minor format issues
> change link to binaries + fixups

- docs/run-a-node/setup/install.md
> Tweak Tip about Rand Labs Windows binaries

- scripts/reformat-all-commands.sh
This should fix the automation failure: https://github.com/algorand/docs/actions/runs/6423610867/job/17442503545
> Ignore nonexistent files during rm

- docs/run-a-node/participate/generate_keys.md
- docs/run-a-node/participate/online.md
- docs/run-a-node/participate/renew.md
Adding and removing partkeys must be done via the cli or API, so manually adding/removing the partkey from the directory is no longer encouraged
Also added some  info
> Removed reference to the partkey directory

- docs/get-details/algokit/index.md
- docs/get-details/algokit/tutorials/intro.md
- docs/get-started/.pages
- docs/get-started/algokit.md
- adds an overview blurb to overview
- adds embedded videos to quick start
- adds install process per os to quick start
> fixup quick start & intro

- docs/get-details/useful_resources.md
updates the Useful Resources page to include Services for Startups
> add service credits

- docs/get-started/algokit.md
`pipx upgrade algokit` to the docs
> add upgrade command
